name: qr_mobile_vision
description: "Plugin for reading QR codes using Firebase's Mobile Vision API."
version: 1.0.1+1
homepage: https://github.com/rmtmckenzie/flutter_qr_mobile_vision

environment:
  flutter: ">=1.24.0-10.2.pre"
  sdk: ">=2.12.0 <3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.github.rmtmckenzie.qrmobilevision
        pluginClass: QrMobileVisionPlugin
      ios:
        pluginClass: QrMobileVisionPlugin

dependencies:
  flutter:
    sdk: flutter
  native_device_orientation: ^1.1.4
